install:
  - if not exist gtk-sharp-2.12.38.msi appveyor DownloadFile http://dl.xamarin.com/GTKforWindows/Windows/gtk-sharp-2.12.38.msi
  - msiexec /i gtk-sharp-2.12.38.msi /qn /norestart
  - if not exist XamarinStudio-6.1.2.44.msi appveyor DownloadFile https://dl.xamarin.com/MonoDevelop/Windows/XamarinStudio-6.1.2.44.msi
  - msiexec /i XamarinStudio-6.1.2.44.msi /qn /norestart

branches:
  only:
  - develop
  - master

build_script:
- ps: .\build.ps1

test: off

artifacts:
- path: ./artifacts/*.mpack
  name: jzeferino.xsaddin  

cache:
- tools -> build.cake, tools\packages.config # Cache \tools until build.cake and/or packages.config change
